### PR TITLE
@trivial - update readme after release

### PR DESCRIPTION
**Pull request by mhaack**

### CODE REVIEW

**Comment by LSantha** [comment]
@mhaack , are there any ee features in this release? I thought that we only require Magento 2.4.2.

**Comment by mhaack** [comment]
I used 2.4.2ee because of https://github.com/adobe/aem-core-cif-components/blob/master/parent/pom.xml#L109, we are not using specific ee features.

**Comment by LSantha** [comment]
OK, that's only the ee version of the library but not Magento. Based on the readme update the users will think that they need Magento ee already.

**Comment by mhaack** [comment]
Updated the readme, removed the ee

**Review by LSantha — APPROVED** [review]

**Review by herzog31 — APPROVED** [review]

**Pull request merged**
