### PR TITLE
CIF-2272 - Cannot close category filter accordion once it is open

### PR DESCRIPTION
**Pull request by LSantha**
Fix closing a filter when it's already opened.

## Related Issue

CIF-2272

## How Has This Been Tested?

Manually, unit test, UI test.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [X] All unit tests pass on CircleCi.
- [X] I ran all tests locally and they pass.

### CODE REVIEW

**Comment by herzog31** [comment]
There should be a test for this change. Like https://github.com/adobe/aem-core-cif-components/blob/master/ui.apps/test/components/commerce/productcollection/productCollectionTest.js.

**Comment by LSantha** [comment]
@herzog31 , I've added a UI test already. See the Venia PR: https://github.com/adobe/aem-cif-guides-venia/pull/179

**Comment by herzog31** [comment]
@LSantha Venia tests are not executed when changes are done in the components repo. So there should be a test in this repo. Can be a UI test or preferably a unit test.

**Comment by LSantha** [comment]
I've added a unit test.

**Review by herzog31 — APPROVED** [review]

**Pull request merged**
