### PR TITLE
Bugfix: PDP displays a bundled product instead of the requested simple product

### PR DESCRIPTION
**Pull request by brandonmaynard**
I am facing an issue where if I try to load a simple product on the PDP, the GraphQL response has 2 products listed. The first product is a bundled product which contains the requested simple product in it. The second product is the actual simple product I expect to be loaded on the PDP. Since the logic just grabs the 0 element of the product array, the bundled product is instead being displayed on the PDP even though the SLUG is the simple product's url_key.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

### CODE REVIEW

**Comment by mhaack** [comment]
@brandonmaynard this LGTM but could you please add a test to cover that case as well. Thx.

**Review by dplaton — APPROVED** [review]
Also, see the unit test comment by @mhaack

**Comment by brandonmaynard** [comment]
Hi @mhaack & @dplaton , thanks for reviewing. I added a small test class. When you have a chance, could you review again?

**Review by herzog31 — APPROVED** [review]

**Comment by mhaack** [comment]
Verified. Thx @brandonmaynard for this contribution.

**Comment by brandonmaynard** [comment]
Thanks all

**Pull request merged**
