### PR TITLE
CIF-2075 - fix NPE from category list with empty objects

### PR DESCRIPTION
**Pull request by mhaack**
## Description

Fix NPE from cases of category list containing h empty (null) objects. This should only happen in exceptional case.

## Related Issue

CIF-2075
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [x] All unit tests pass on CircleCi.
- [x] I ran all tests locally and they pass.

### CODE REVIEW

**Comment by herzog31** [comment]
Can you extend https://github.com/adobe/aem-core-cif-components/blob/master/bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java for this new case please?

**Review by LSantha — APPROVED** [review]

**Comment by LSantha** [comment]
@mhaack , how did you get this error?

**Comment by mhaack** [comment]
@LSantha while testing with Hybris integration and debugging together with Diconium. Their backend returned incorrect data, so this might be rare to break in the field.

**Comment by mhaack** [comment]
@herzog31 done, covered new cases and improved test

**Review by herzog31 — APPROVED** [review]

**Pull request merged**
