### PR TITLE
CIF-1608 - Category Carousel Component

### PR DESCRIPTION
**Pull request by LSantha**
* enhanced featured category list component to category carousel
 * rebranded featured category list component as Category Carousel
 * added unit tests for category carousel client library

## Related Issue

CIF-1608

## How Has This Been Tested?

Manually, karma tetst.

## Screenshots (if appropriate):
categories

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes and the overall coverage did not decrease.
- [X] All unit tests pass on CircleCi.
- [X] I ran all tests locally and they pass.

### CODE REVIEW

**Review by mhaack — COMMENTED** [review]
Some general comments on this:

* Since the markup of the component is changed it will break existing customers if the did styling or customizations -> hence I think we should not touch the initial component and add the new carousel flavor in a `v2` 
* The clientlib containing the category-carousel.js is a lot of duplication to the product carousel, can this be done smarter?

**Comment by LSantha** [comment]
@mhaack , I think both points are valid. Actually I've been investigating an other solution too which would address both points and go beyond but opened these PRs on Friday to closely match the solution that we discussed on the technical grooming. 
After all this I'm certainly in favor of a more comprehensive redesign where we clarify better backwards compatibility concerns and strategy for evolving the components.

**Review by dplaton — APPROVED** [review]

**Comment by mhaack** [comment]
> After all this I'm certainly in favor of a more comprehensive redesign where we clarify better backward compatibility concerns and strategy for evolving the components.
... what does this mean? Are you closing this PR an create a new one?

**Comment by LSantha** [comment]
I can close this and create a new PRs (all 3 will be different), we can discuss it in the grooming tomorrow.

**Pull request closed without merging**
