### PR TITLE
CIF-1906 - Minimal default styling for category carousel

### PR DESCRIPTION
**Pull request by LSantha**
Created minimal styling for carousel and category carousel.

## Related PRs
https://github.com/adobe/aem-project-archetype/pull/597
https://github.com/adobe/aem-cif-guides-venia/pull/100

## Related Issue

CIF-1906

## How Has This Been Tested?

Manually.

## Screenshots (if appropriate):
categorycarousel

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [X] All unit tests pass on CircleCi.
- [X] I ran all tests locally and they pass.

### CODE REVIEW

**Review by dplaton — APPROVED** [review]

**Comment by mhaack** [comment]
Can we remove the circle? This is already extra styling, lets just display the rectangular image.

**Comment by LSantha** [comment]
I kept the circle only to visually differentiate products from categories, but it's controlled only by the border-radius property and can be easily removed or modified.

**Comment by mhaack** [comment]
If easy to remove the please remove. This is already an extra style and opinonated decision we take. Why circle? Who not tringale ;-) lets just really keep it at a minimun.

**Comment by LSantha** [comment]
OK: overly round square transformed to square. :)

**Review by dplaton — APPROVED** [review]

**Review by mhaack — APPROVED** [review]
Thanks.

**Pull request merged**
