### PR TITLE
Issue/brand slug

### PR DESCRIPTION
**Pull request by nishneo**
## Description

Brandslug from page properties is not coming on page title when using CIF page component

### CODE REVIEW

**Comment by mhaack** [comment]
Brand slug was added in https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.14.0 we currently still have only WCM core components 2.9.0 dependency. This should be aligned.

**Review by dplaton — APPROVED** [review]

**Review by Buuhuu — COMMENTED** [review]
@LSantha can this be done together with CIF-2211?

**Comment by mhaack** [comment]
With CIF-2211 closed now can this be merged? @LSantha wdyt?

**Comment by mhaack** [comment]
Replaced by #662

**Pull request closed without merging**
