### PR TITLE
CIF-1785 - Implement ComponentExporter for category carousel component

### PR DESCRIPTION
**Pull request by cjelger**
- fixed returned resource type for json export for all components

The `categorycarousel` reuses the `FeaturedCategoryList` sling model but the model wrongly returned the "hard-coded" CIF component type. To align with what the WCM core components do, and what is done in the datalayer, I changed all components already implementing `ComponentExporter` to return the actual resource type. This "fixes" the export for the `categorycarousel` component and for all other components.

## How Has This Been Tested?

Adapted unit tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [x] All unit tests pass on CircleCi.
- [x] I ran all tests locally and they pass.

### CODE REVIEW

**Review by laurentiumagureanu — APPROVED** [review]

**Comment by dplaton** [comment]
> the model wrongly returned the "hard-coded" CIF component type

This was by design. In the SPA you need to map the React component to the AEM resource type using a call like
```javascript
MapTo(`aem/resource/type`)(ReactComponent)
```
If you use the "Venia" resource type then you are creating a hard link between a project name and the React Components, greatly reducing SPA components reusability, since all the component mappings would have to be adjusted for every project.

**Comment by cjelger** [comment]
@dplaton Thanks for clarifying this, but I checked the WCM Core components and they export the actual/real resource type with `resource.getResourceType();` ... I actually think that the archetype would (should?) generate the correct SPA and React components with the proper `MapTo(...)` values, WDYT? I'll also check this.

**Comment by dplaton** [comment]
@cjelger that's an interesting approach, but I think we have a slightly different workflow: our React components (at least the ones that currently consume these Sling Models are meant to work as a PWA Studio extension. Developers would just have to install this extension as a dependency to their PWA Studio app, configure it, and that's it. There's no archetype involved here.

I must admit the situation is a bit murky here. We don't have support from the editor (yet) which is the main pain point, that's why we didn't bother much with the rest of it (like how a project would be bootstrapped etc)

**Comment by dplaton** [comment]
There are solid reasons for this update, but this will break some existing code. Since the SPA Editor feature is still WIP I'll put this into "draft" status for the moment.

**Comment by dplaton** [comment]
Closing for now, but I'll leave the branch in the repository.

**Pull request closed without merging**
